name: HWHBEAR Assignment

on:
  push:
    branches:
      - 'feature-01'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#NORUN')"
    steps:
      - name: Hnin code
        uses: actions/checkout@v3

      - name: Hnin js Code
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Hnin Railway
        run: npm i -g @railway/cli

      - name: Hnin Railway up to
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.SNOWCICD }}

      - name: Hnin slack
        uses: slackapi/slack-github-action@v1.23.0
        id: slack-notify
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "DipSA 56 CI/CD Submission",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "Name:\nHnin Wutt Hsan"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Email:\ne1112929@u.nus.edu"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Matriculation:\nE1112929"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Repository:\n${{ github.event.repository.html_url }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "https://${{ secrets.SNOWRAILWAY }}.up.railway.app/"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go",
                      "emoji": true
                    },
                    "url": "https://${{ secrets.SNOWRAILWAY }}.up.railway.app/"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK